### ISSUE TITLE
Feeds: urlencode nested-zip URI fragments

### ISSUE THREAD

**Issue by irees** [transitland/transitland-datastore#1022]
Ruby's URI parser doesn't like spaces:

`http://www.vbb.de/de/download/GTFS_VBB_Dez2016_Dez2017.zip#GTFS_VBB_Dez2016 Dez2017_mit_shape_files.zip`

urlencode this to:

`http://www.vbb.de/de/download/GTFS_VBB_Dez2016_Dez2017.zip#GTFS_VBB_Dez2016%20Dez2017_mit_shape_files.zip`

**Comment by stevevance** [comment]
The problem is here: https://github.com/transitland/transitland/issues/56
