### ISSUE TITLE
Incorrect is_active_feed_version in api/v1/feed_versions

### ISSUE THREAD

**Issue by markerpen** [transitland/transitland-datastore#1023]
Hi all,

Just trying to get the latest GTFS feed from Dallas DART, and I've noticed that when using the `feed_versions` endpoint it shows all feeds that have been consumed, but an older feed still has the `is_active_feed_version` tag set to **true**, while the latest feed (and the current one) still shows as **false**.

Here's the URL I'm using: `https://transit.land/api/v1/feed_versions?feed_onestop_id=f-9vg-dallasarearapidtransit&sort_key=fetched_at&sort_order=desc&per_page=10`

And here's the data I'm getting back (edited for brevity)

```
{
  "feed_versions": [
    {
      "sha1": "98a184a84c4c1e495d8585e0b6e95b36fad0d29e",
      "earliest_calendar_date": "2017-03-13",
      "latest_calendar_date": "2017-09-24",
      "md5": "0eb014dedab1dd03c214a73e74f656f9",
      "tags": {
        "feed_lang": "en",
        "feed_version": "118-119-1",
        "feed_publisher_url": "http://www.dart.org",
        "feed_publisher_name": "DALLAS AREA RAPID TRANSIT"
      },
      "fetched_at": "2017-02-28T14:00:12.068Z",
      "created_at": "2017-02-28T14:00:12.131Z",
      "updated_at": "2017-02-28T14:00:12.131Z",
      "is_active_feed_version": false,
    },
    {
      "sha1": "4f617b4eb34c675104717f7c882b0c14f2b8a9ea",
      "earliest_calendar_date": "2017-03-13",
      "latest_calendar_date": "2017-09-24",
      "md5": "686369befcfca121cbb12d8b2be930ad",
      "tags": {
        "feed_lang": "en",
        "feed_version": "118-119-1",
        "feed_publisher_url": "http://www.dart.org",
        "feed_publisher_name": "DALLAS AREA RAPID TRANSIT"
      },
      "fetched_at": "2017-02-24T15:00:11.590Z",
      "created_at": "2017-02-24T15:00:11.650Z",
      "updated_at": "2017-02-24T15:00:11.650Z",
      "is_active_feed_version": false,
    },
    {
      "sha1": "07f25dc0a1adc76148c99a0368451c307308bbc0",
      "earliest_calendar_date": "2016-10-24",
      "latest_calendar_date": "2017-03-12",
      "md5": "6694fca0a0c116177292ef71249b9976",
      "tags": {
        "feed_lang": "en",
        "feed_version": "114-112-1",
        "extend_to_date": "2018-03-12",
        "extend_from_date": "2017-02-12",
        "feed_publisher_url": "http://www.dart.org",
        "feed_publisher_name": "DALLAS AREA RAPID TRANSIT"
      },
      "fetched_at": "2016-12-21T03:30:13.032Z",
      "created_at": "2016-12-21T03:30:13.110Z",
      "updated_at": "2017-03-05T14:13:27.210Z",
      "is_active_feed_version": true,
      
    },
    ...
  ],
  "meta": {
    "sort_key": "fetched_at",
    "sort_order": "desc",
    "offset": 0,
    "per_page": 10
  }
}
```

Can anyone help? I've got a script running that checks each feed for `is_active_feed_version`, and downloads the GTFS file if it exists.

**Comment by drewda** [comment]
Hi @markerpen, thanks for your question.

The `is_active_feed_version` flag designates the latest version of the feed that has been imported into the Transitland Datastore. For example, when querying the `ScheduleStopPair` endpoint, you will be accessing schedule data imported from this feed version. There can be a lag between when a new feed version is fetched and when it is imported--for example, in some cases, the calendar entries are not yet active.

Using your query URL, you can just change to `per_page=1` and you will always get the latest feed version fetched (whether or not it is the latest version to be imported into the Transitland Datastore).

Alternatively, if you'd like to skip a step, give a try with an endpoint we have added recently: https://transit.land/api/v1/feeds/f-9vg-dallasarearapidtransit/download_latest_feed_version

If this does not fully answer your question, please reopen.
