### ISSUE TITLE
Changesets: examine array uniqueness requirements

### ISSUE THREAD

**Issue by irees** [transitland/transitland-datastore#1059]
These may not be necessary, and at worst cause small amounts of extra work during changeset apply. However, they are a source of frustration when manually editing or merging change payloads.

**Comment by stevevance** [comment]
This happens when there are duplicate operators in a feed. 

Right now this is preventing me from applying the new Perth payload.

**Comment by irees** [comment]
Resolved by https://github.com/transitland/transitland-datastore/pull/1160
