### ISSUE TITLE
API not returning objects when requested by gtfs_id

### ISSUE THREAD

**Issue by ldnash** [transitland/transitland-datastore#1070]
For example, trying this query from the API documentation,
https://transit.land/api/v1/routes?imported_with_gtfs_id=true&gtfs_id=Lo-16APR

Gives this result:
`{"routes":[],"meta":{"sort_key":"id","sort_order":"asc","offset":0,"per_page":50}}`

**Comment by irees** [comment]
Hi @ldnash 

Ah, thanks for catching that. The correct query is:
https://transit.land/api/v1/routes?imported_with_gtfs_id=Lo-16APR

I'll update the documentation now.

**Comment by ldnash** [comment]
Ah, okay! Thanks for the quick response.

**Comment by irees** [comment]
@ldnash 

Looking into it - it was an accidental change. I am updating the API to allow both styles, with the GTFS ID in either `imported_with_gtfs_id` or `gtfs_id`.

See: #1071
