### ISSUE TITLE
Unique onestopid operator

### ISSUE THREAD

**Issue by slvlirnoff** [transitland/transitland-datastore#1091]
While submitting a feed I had an issue with an invalid changeset, I've narrowed it down to two or more operators with the same onestopid, I was able to fix it by manually editing the changeset.

It seems that if two operator have the same agency name and geo hash they will have the same onestopid and this make the feedinfo for the feed registry not usable as is.

We could probably use agency_Id in the onestopid if already used/duplicated.

I'm happy to try to submit a fix but I'd like some directions for the best approach.

Best,
Cyprien

**Comment by drewda** [comment]
@slvlirnoff thanks for writing in.

If the same operator is used in two or more different feeds, the goal is to recognize this and connect those feeds with the same operator records. For example, New York MTA is represented across 6 feeds: https://transit.land/feed-registry/operators/o-dr5r-nyct

Is your use case different than this? Can you provide more information on the feed(s) and agencies/operators you're trying to run through the FeedInfo service?

**Comment by slvlirnoff** [comment]
Hi,

Thanks for the info, I wasn't sure about multi feed supporting the same operator.

This might different and maybe more an issue of feed-registry. If you have two agency in the same feed that resolve to the same onestopid the resulting changeset is invalid. 

The changeset seems to generate two (or more) entries that all refer to the same agency Id. Not sure if it fails because multiple createUpdate with same operator Id. Or multiple operator linking to the same gtfs agency id. 

Should I open a ticket in the feed-registry instead? 

Best
Cyprien

**Comment by slvlirnoff** [comment]
@drewda the feed I'm having issues with is the greater sydney feed (new south wales), that can be found here: https://opendata.transport.nsw.gov.au/documentation

**Comment by drewda** [comment]
The Transport for NSW feed was successfully added in this changeset: https://transit.land/dispatcher/changesets/6045

Previously there were issues adding that feed, but they were resolved on https://github.com/transitland/transitland/issues/38

@slvlirnoff if you encounter more problems with this feed, please reopen this issue and list out the steps we can follow to reproduce the problem. Thanks!
