### ISSUE TITLE
Stop becomes StopPlatform

### ISSUE THREAD

**Issue by irees** [transitland/transitland-datastore#1103]
Stop loaded by gtfs `stop_id` is trying to be used as a StopPlatform, fails with `no method parent_stop`

See: https://transit.land/dispatcher/feed-versions/8673f2521c88085f612d302abef70d6103dcebf7

**Comment by drewda** [comment]
Potentially the root cause of https://github.com/transitland/transitland/issues/226

**Comment by irees** [comment]
Some more examples, this time in demo feeds:
https://transit.land/dispatcher/feed-versions/544f40785a1146a393806c55ae1a5c925af2942b
https://transit.land/dispatcher/feed-versions/401ba403a62f37be32ebab324a1aa8bd0d3d6ef8
https://transit.land/dispatcher/feed-versions/4cfbeacfe73638e646757e3b73f1fecabef8f598

**Comment by irees** [comment]
Testing using:
https://transit.land/dispatcher/feeds/f-9xj-rtd

which exists on both dev & prod
