### ISSUE TITLE
RSPs missing trips

### ISSUE THREAD

**Issue by doublestranded** [transitland/transitland-datastore#1104]
I've been seeing this in recent imports. An example:

https://transit.land/api/v1/route_stop_patterns?imported_from_feed=f-dpxj-hamiltonstreetrailway

**Comment by irees** [comment]
@doublestranded I've started storing trips through EntitiesImportedFromFeed... RSP EIFFs are the `trip_id`s.

**Comment by irees** [comment]
I have a PR coming up that fixes `with_trips` to use the EIFFs.
