### ISSUE TITLE
API queries timing out

### ISSUE THREAD

**Issue by christrillium** [transitland/transitland-datastore#1240]
I've been trying to query the transit.land API today, but all the requests keep timing out before any results are returned. 
For example, the sample query posted on the [API documentation page](https://transit.land/documentation/datastore/api-endpoints.html) does not work.
https://transit.land/api/v1/routes?operated_by=o-9q8y-sfmta

**Comment by irees** [comment]
hi @christrillium -- I tweaked some resource allocations and restarted some front-end instances. The query above seems to working now - let me know if it continues to be an issue.

**Comment by drewda** [comment]
Closing, we can re-open if the issue re-occurs.
