### ISSUE TITLE
Regression on operator-associated metadata?

### ISSUE THREAD

**Issue by kuanb** [transitland/transitland-datastore#1255]
Jacksonville's transit feed used to include a Metro area ("Jacksonville"). Querying the API today, Oct. 09, 2018), I see in the response that `f-djmu-jacksonvilletransportationauthority`'s associated `metro` attribute is a `None` value.

Lacking familiarity with how the operator feed metadata is managed; is this possible? Is an operator able to "lose" associated attributes, such as `metro`? 

(In a tool I use that pulls down transit data updates, I've relied on the presence and consistency of the `metro` attribute for a given operator, but should probably update my logic if this is not an attribute that remains constant.)

**Comment by drewda** [comment]
Hi @kuanb, I just looked on the internal console and it doesn't appear that the operator with Onestop ID of `o-djmu-jacksonvilletransportationauthority` ever had a `metro` value assigned -- note all the nil values:

```rb
irb(main):006:0> pp Operator.find_by_onestop_id('o-djmu-jacksonvilletransportationauthority').old_versions.pluck(:metro, :created_at)
[[nil, Fri, 03 Aug 2018 20:35:42 UTC +00:00],
 [nil, Wed, 06 Jun 2018 02:03:24 UTC +00:00],
 [nil, Sun, 19 Nov 2017 15:03:49 UTC +00:00],
 [nil, Thu, 17 Aug 2017 15:50:45 UTC +00:00],
 [nil, Tue, 04 Apr 2017 15:19:44 UTC +00:00],
 [nil, Fri, 24 Feb 2017 18:43:36 UTC +00:00],
 [nil, Wed, 25 Jan 2017 19:46:21 UTC +00:00]]
```

FYI, `metro` is a model-level attribute on the `Operator` model. It's set by a `Changeset` created by a user. Unlike some other model-level attributes, there are no automated processes that set `metro`. Typically it's just what a feed-submitter or a moderator adds to the form as part of the [add a feed flow](https://transit.land/feed-registry/feeds/new). There's the potential for a user or a moderator to (intentionally) change the `metro` value. If you need a truly stable reference, use a Onestop ID instead.

**Comment by kuanb** [comment]
Gotcha; makes sense. Thanks again @drewda for this explanation - really helpful!
