### ISSUE TITLE
Operators not returned in bounding box query

### ISSUE THREAD

**Issue by kuanb** [transitland/transitland-datastore#1256]
When I query for all feeds in the following bounding box:
![image](https://user-images.githubusercontent.com/6053396/46770466-58201300-cca4-11e8-8334-4ec3dab1a9db.png)

Via the below method:
```
import requests

bbox = '-123.0555,44.029,-121.3206,44.1252'
op_query_base = 'http://transit.land/api/v1/operators'

resp_json = requests.get(op_query_base,
                         data={'bbox': bbox}).json()

ops_with_metro = [op['onestop_id']
                  for op in resp_json['operators']]

print('=== Got feeds ===')
[print(o) for o in ops_with_metro]
```

I receive the following operators back:
```
=== Got feeds ===
o-9rc-cascadeseasttransit
o-9rb-cascadespoint
o-9rb-city2cityshuttle
o-9rb-diamondexpress
o-9r-easternpoint
o-9rb-eugenetocoosbay
o-9rc-highdesertpoint
o-9rb-hutairportshuttlephoneorwebreservationsrequiredforthisservice
o-9r-peoplemover
o-9rb-valleyretriever
o-9-amtrak
o-9-amtrakcharteredvehicle
o-9rb-lanetransitdistrict
o-9rc-centraloregonbreeze
o-9rb-pacificcrestlines
o-9rb-oregonexpressshuttle
```

Yet, I happen to know transitland has an additional operator in that area, which I can view here:
```
https://transit.land/api/v1/feeds/f-9rc-eugenetobend~or~us
```

Plotting the bounds for that operator shows it lies within/intersects the bounds of my previous query:
![image](https://user-images.githubusercontent.com/6053396/46770512-96b5cd80-cca4-11e8-8feb-3957ca13eb6e.png)

Is there a specific reason it is not being shown in the bounding box query results?

**Comment by drewda** [comment]
There are no operators associated with the `f-9rc-eugenetobend~or~us` feed. (See `operators_in_feed: []`) Thus the feed bounding box will appear in queries to `/api/v1/feeds` but no matching operators will appear in queries to `/api/v1/operators`

This feed hasn't been updated in years. It's kept for historical purposes.

**Comment by kuanb** [comment]
Thank you for the clarification @drewda
