### ISSUE TITLE
Active feed version is too old

### ISSUE THREAD

**Issue by elsa-pato** [transitland/transitland-datastore#1296]
Hi,
I'm having a problem with two feeds, where the active feed version is outdated (the schedule provided were valid until December 2019 only), and the newest feed version is not imported. When I query the schedule API, I don't get any result back
https://transit.land/api/v1/schedule_stop_pairs?date=today&origin_onestop_id=s-spey67f167-strasbourgamiens

Is there a way to trigger the update the active feed ?

Feeds :
https://transit.land/feed-registry/operators/o-spe-car13
https://transit.land/feed-registry/operators/o-spey-rtm

**Comment by drewda** [comment]
Hi @elsa-pato thanks for your note and interest. We've noticed that one of the background queues for Transitland imports failed recently. We've now fixed it. Over the next hours and days, the background processes will catch up with these imports again.

**Comment by elsa-pato** [comment]
great, thanks for your quick answer !
