### ISSUE TITLE
Possible to query all feeds from a specified country with API? 

### ISSUE THREAD

**Issue by nuistzhou** [transitland/transitland-datastore#1303]
I tried to find if a 'country' parameter exists, but failed.

**Comment by drewda** [comment]
In the v1 Datastore, you can query for operator records with a `country` query parameter, and then look up the corresponding feeds. The feed endpoint cannot look up by country.

In the v2 REST API, you can query for either operator, feed, or agency by country (using `adm0_name` or `adm0_iso1`): https://www.transit.land/documentation/rest-api/agencies
