### ISSUE TITLE
API gives same results for different queries

### ISSUE THREAD

**Issue by srthurman** [transitland/transitland-datastore#164]
Some of the API endpoints, specifically those using "identifer_starts_with", give the same results regardless of the input. For instance:
https://transit.land/api/v1/stops?identifer_starts_with=gtfs://f-9q9 & https://transit.land/api/v1/stops?identifer_starts_with=gtfs://f-dhw

Looking through the code, it looks like "identifer" and "identifier" are both used, in case that is contributing to this issue.

**Comment by drewda** [comment]
Thanks for noticing, @srthurman. We certainly do have typos. Fix coming soon.

**Comment by drewda** [comment]
FYI, this will be fixed by some other changes we'll be deploying to production soon.

**Comment by drewda** [comment]
The following queries (and any others involving identifiers) should now work:

- https://transit.land/api/v1/stops?identifier_starts_with=gtfs://f-9q9
- https://transit.land/api/v1/stops?identifier_starts_with=gtfs://f-dhw
