### ISSUE TITLE
Station Hierarchy data model

### ISSUE THREAD

**Issue by irees** [transitland/transitland-datastore#256]
Implement Station Hierarchy model.

- [x] Station: New model
- [x] Station: Stop STI: Stop, StopPlatform, StopEgress
- [x] Station: has many stops
- [x] Station entrance: connected_osm_way_id
- [ ] Update Station Hierarchy Diagram

**Comment by drewda** [comment]
+-----------------------------+
 | Stop                        |
 |-----------------------------|
 |                             |
 | - ID: gtfs://f-9q9-bart/3422|+-------------------> OperatorServingStop +----> Operator
 | - location_type             |
 | - parent_station            |
 | - station_onestop_id        |+-------------------> RouteServingStop +--------> Route
 | - feed version SHA1's       |
 | - geom                      |
 | - other GTFS columns...     |
 +-----------------------------+




   +-----------------------------------+
   |Station [polymorphic table]        |
   |-----------------------------------|
   |- onestop_id "s-9q8yy-Civic~Center"|
   |- name                             |
   |- stop_ids                         |
   |- tags                             |
   |- geometry (point or poly)         |
   +-----------------------------------+
     ^ ^
     | |    +----------------------------------------------+
     | |    |StationEntrance                               |
     | |    |----------------------------------------------|
     | |    |- onestop_id "s-9q8yy-Civic~Center>8th~Market"|
     | |    |- connected_osm_way_id                        |-------------> OpenStreetMap
     | |    |                                              |               pedestrian
     | |    |                                              |               network
     | |    |                                              |
     | +----|- station_id                                  |
     |      |- geometry (point)                            |
     |      +----------------------------------------------+
     |
     |      +-------------------------------------+
     |      |StationPlatform                      |
     |      |-------------------------------------|
     |      |- onestop_id "s-9q8yy-Civic~Center<2"|
     |      |                                     |<--------------+ OperatorServingStationPlatform
     |      |                                     |
     |      |                                     |<--------------+ RouteServingStationPlatform
     +------|- station_id                         |
            |- geometry (point or poly)           |+--------------> ScheduleStopPair
            +-------------------------------------+

**Comment by irees** [comment]
```
+-----------------------------+
| BaseStop (Abstract)         |
|-----------------------------|
|- onestop_id                 |
|- name                       |
|- identifiers                |
|- timezone                   |
|- last_conflated_at          |
|- osm_way_id                 |
|- tags                       |
|- geometry                   |
|- parent_station             |
+-----------------------------+

+-----------------------------------+
| Stop < BaseStop                   |
|-----------------------------------|
|- Stand alone Stop                 |
|- No parent_station                |+----> ScheduleStopPair
|- geometry is point                |
+-----------------------------------+

+-----------------------------------+
| StopStation < Stop                |
|-----------------------------------|
|- Promoted from Stop               |
|- No parent_station                |
|- No osm_way_id, last_conflated_at |
|- geometry is point                |
+-----------------------------------+
    ^  ^
    |  |   +-------------------------------------+
    |  |   | StopEgress < Stop                   |
    |  |   |-------------------------------------|
    |  |   |- onestop_id >                       |
    |  +---+- parent_station required            |
    |      |- osm_way_id required                |
    |      |- geometry is polygon convex hull    |
    |      +-------------------------------------+
    |
    |      +-------------------------------------+
    |      | StopPlatform < Stop                 |
    |      |-------------------------------------|
    |      |- onestop_id <                       |<----+ OperatorServingStationPlatform
    +------+- parent_station required            |<----+ RouteServingStationPlatform
           |- geometry (point or poly)           |+----> ScheduleStopPair
           +-------------------------------------+

http://stable.ascii-flow.appspot.com/#Draw
```
(originally attached to wrong issue)

**Comment by irees** [comment]
Station hierarchy API mockup: https://gist.github.com/irees/7f62fbed50f0bc2c749eca4eca1677d3
