### ISSUE TITLE
use Onestop IDs as primary and foreign keys (to reduce needs for cross-table joins)

### ISSUE THREAD

**Issue by drewda** [transitland/transitland-datastore#278]
open question: What should the primary key be on `old_stops`, `old_feeds`, etc.? Records will be unique by the combination of Onestop ID and version integer--but not unique by Onestop ID alone.

Some options:
- continue to use integer primary keys on old tables
- investigate compound keys in Postgres and ActiveRecord (Onestop ID string + version integer): https://github.com/composite-primary-keys/composite_primary_keys

Another open question: Does this make it harder to do polymorphic associations? For example, an `OldRouteServingStop` can be associated with a current stop or an old stop. Right now `stop_id` is an integer column, but it would need to be changed to a string column if Onestop ID becomes the primary key for the Stop model

related to #276

**Comment by irees** [comment]
I generally like the idea of Onestop ID as primary keys, and either integer ID or (Onestop ID, Version) composite keys on old tables.

**Comment by irees** [comment]
Using onestop_id as primary key works great, except for SSPs. Entities_imported_from_feed is polymorphic and changing entity_id to string (to reference onestop_ids) then breaks referencing SSP IDs, which are still integers.
