### ISSUE TITLE
RouteStopPatterns (and improved route geometries)

### ISSUE THREAD

**Issue by drewda** [transitland/transitland-datastore#279]
Overall requirements: 

 - Queryable from Route endpoint (for playground & other GeoJSON users)
 - Queryable by ID (for routing)
 - Distance: start_distance, end_distance

RouteStopPattern model:

 - Query by bounding box

- [x] Enable SSP distances and RSP association in SSP serializer
- [x] Move OnestopId refactoring into separate branch/pull request
- [x] Move RGeo functionality to initializer (and note potential RGeo pull request contribution). Remove Haversine gem.
- [x] Project to Cartesian features and test https://github.com/rgeo/rgeo/issues/99 (implement Spherical functionality if not successful)
- [x] Work with Ian to figure out where to put distance calculation in GTFSGraph
- [x] Determine what to add to Route/RSP controllers beyond basic queries
- [x] Automated testing of RSP controller
- [x] Handle Polymorphic type in changeset (before/update/after) implementation 
- [x] Merge migrations for concise branch

**Comment by doublestranded** [comment]
- [ ] rspecs
- [ ] docs (with potential help from Rhonda)
- [ ] diagrams (with potential help from Ekta)
- [ ] blog post

**Comment by doublestranded** [comment]
- [ ]  add attributes to geojson

**Comment by doublestranded** [comment]
- [ ]  refactor "find_rsp" methods from GTFSGraph into RSP model

**Comment by doublestranded** [comment]
- [ ] create repository within transitland for RSP visualizer tool

**Comment by doublestranded** [comment]
For the documentation checklist item: documentation will be added to /doc (create route-stop_patterns.md) and README.md.
Include explanations of calculating distances.
