### ISSUE TITLE
GtfsGraph refactoring

### ISSUE THREAD

**Issue by drewda** [transitland/transitland-datastore#288]
will enable #257

**Comment by irees** [comment]
Cleared up all/most of the Rubocop/HoundCI comments, this is now ready to merge.

**Comment by irees** [comment]
@doublestranded Small changes needed to work with your RSP branch. 1) update create_change_payload calls. 2) Set rsp traversed_by to the route onestop_id string; it will picked up via 'virtual_attributes' and passed into the change as traversedBy.

**Comment by irees** [comment]
@doublestranded I did a test merge of the as-change branch and rsp branch locally, and it turns out there are a few conflicts and will require a bit more work to merge with rsp branch. We can do it together when I return.
