### ISSUE TITLE
handle GTFS feeds with `calendar_dates.txt` but no `calendars.txt`

### ISSUE THREAD

**Issue by drewda** [transitland/transitland-datastore#308]
The GTFS spec requires a `calendars.txt` file, but some agencies, like WMATA in Washington, D.C., skip it and only include a `calendar_dates.txt` file.

To handle these situations:

- [x] populate `FeedVersion.earliest_calendar_date` and `FeedVersion.latest_calendar_date` using `calendar_dates.txt`
- [x] update `GtfsGraph` to also build `ScheduleStopPair`s using only `calendar_dates.txt`
- [x] update `GTFS::ServicePeriod` in [Ruby library](https://github.com/transitland/gtfs) if possible

**Comment by drewda** [comment]
```ruby
   def read_gtfs_calendar_dates
     if file.present? && file_changed?
       gtfs_file = GTFS::Source.build(file.path, {strict: false})
       begin
         # for feeds that include calendars.txt
         self.earliest_calendar_date ||= gtfs_file.calendars.map {|c| c.start_date}.min
         self.latest_calendar_date   ||= gtfs_file.calendars.map {|c| c.end_date}.max
       rescue GTFS::InvalidSourceException
         # for feeds that only include calendar_dates.txt (like WMATA)
         # even though that goes against the GTFS spec
         self.earliest_calendar_date ||= gtfs_file.calendar_dates.map {|c| c.date}.min
         self.latest_calendar_date   ||= gtfs_file.calendar_dates.map {|c| c.date}.max
       end
     end
   end
```

**Comment by drewda** [comment]
N.B.: Turns out the GTFS spec is ambiguous. It [indicates that `calendar.txt` is required](https://developers.google.com/transit/gtfs/reference?hl=en#calendartxt) but then it says ["Alternate: Omit calendar.txt, and include ALL dates of service in calendar_dates.txt"](https://developers.google.com/transit/gtfs/reference?hl=en#calendar_datestxt).

More reason for us to support both styles.

**Comment by irees** [comment]
Working on this now.

**Comment by irees** [comment]
So, I mis-remembered. The Python loader handled this, the Ruby loader needs an update to handle feeds without calendar.txt. Fix coming.

**Comment by irees** [comment]
All these cases should now be handled correctly in the GTFS wrapper PR referenced above. Additionally, the Source#service_period_range will now return the earlier/lastest service period date combining both calendar files, and may be used in FeedInfo.
