### ISSUE TITLE
handle ZIP files that contain nested GTFS feeds (and CSV files in a nested directory)

### ISSUE THREAD

**Issue by drewda** [transitland/transitland-datastore#316]
Currently the Transitland Datastore API, FeedInfo and FeedFetcher workers, and the Feed Registry "add a feed" flow only support and ingest ZIP files that contain a single GTFS feed. But some operators combine together multiple GTFS feeds into a set of nested ZIP files.

To support these situations:

1. [ ] FeedInfo parses all nested ZIP files and returns multiple `Feed` models
2. [ ] Feed Registry "add a feed" flow UX changes https://github.com/transitland/feed-registry/issues/123
3. [ ] Datastore `Feed` model keeps track of the path to the nested ZIP file

Some thought and discussion required for (2) and (3), so we can hold on this for now.

---

See also the programatic approach taken by @flibbertigibbet on https://github.com/azavea/gtfs-feed-fetcher

---

A related situation is when a ZIP file only contains one feed, but its CSV files are not in the root directory of the ZIP file. For example, [the Nairobi feed](https://github.com/transitland/transitland/issues/32). To handle this we could also:

4. [ ] Datastore `Feed` model keeps track of the path to a nested directory (which contains the feed's CSV files)

**Comment by msmollin** [comment]
+1'ing this as well for SEPTA support.
