### ISSUE TITLE
Onestop ID lineage/deaccessioning

### ISSUE THREAD

**Issue by drewda** [transitland/transitland-datastore#332]
changing the Onestop ID on an entity
- [x] a new changeset action: `changeOnestopID`
- [x] when the changeset is applied, it sets `action=change_onestop_id` in the `old_` entities record
- [x] `find_by_onestop_id` methods will now search through both the `current_` and `old_` entities records. Will redirect to the entity with the current Onestop ID

destroying an entity with a Onestop ID
- uses the existing `destroy` changeset action
- [x] when the changeset is applied, it sets `action=destroy` in the `old_` entities record
- [x] `find_by_onestop_id` methods will now search through both the `current_` and `old_` entities records before returning their results. If a Onestop ID has been deleted, the API will indicate that.

merging entities with multiple Onestop IDs into one
- [x] add new `merge`changeset action that takes in an array of Onestop IDs and one entity/Onestop ID for the target/survivor
- [x] when the changeset is applied, set `action=merge` in the `old_` entity records and point their `current` column to the target/survivor
- [x] `find_by_onestop_id` methods will now search through both the `current_` and `old_` entities records before returning their results. For merged records, redirect to the target/survivor

- [ ] add callbacks to merge and change. Specifically, when Feed onestop id changes, the S3 link might need updating (related to #895; may not be an issue), and the stop_pattern onestop id in the RouteStopPattern stop_pattern attributes needs to be updated. 

After this is in place:
- When geometry changes outside of a Onestop ID's geohash, automatically change the geohash

**Comment by doublestranded** [comment]
Questions:
1) When to change OnestopId?
2) What should happen when changed
3) How should it be renamed?
4) How should old references be kept discarded?

**Comment by drewda** [comment]
***actions available through changesets***

to rename a Onestop ID:
```json
"action": "changeOnestopId",
"existingOnestopID": "x-xxxx-old",
"newOnestopId": "x-xxxx-new"
```

to destroy an entity with a Onestop ID: same as existing `destroy` action

to merge 1 or more entities into a single Onestop ID:
```json
"action": "merge",
"onestopIdsToMerge": ["x-xxx-1", "x-xxx-2", "x-xxx-3"],
"operator": {
  "onestopID": "x-xxx-3"
}
```

**Comment by doublestranded** [comment]
![](https://files.slack.com/files-pri/T065YL1LH-F3GSXPN1K/20161219_150618.jpg)

![](https://files.slack.com/files-pri/T065YL1LH-F3GSVKKRT/20161219_150613.jpg)

**Comment by doublestranded** [comment]
![20161219_150618](https://cloud.githubusercontent.com/assets/3828027/21332649/bd4c6eda-c5fe-11e6-8ef8-b9d5c15d9740.jpg)
![20161219_150613](https://cloud.githubusercontent.com/assets/3828027/21332650/bf8e80ca-c5fe-11e6-89b4-d0bd3ac65636.jpg)

**Comment by doublestranded** [comment]
- [ ] update the S3 filename to include *only* the sha1 hash and not the feed onestop id
- [ ] remove renaming of S3 links on change onestop id

**Comment by doublestranded** [comment]
Note: a change onestop id action now requires two id fields: "newOnestopId" and "onestopId"
