### ISSUE TITLE
RSP followup improvements

### ISSUE THREAD

**Issue by irees** [transitland/transitland-datastore#336]
- Geometry simplification / precision
- Add RSP integration tests
- Spec style improvements
- Spec for route geometry (uniq)
- RSP OSID specs

**Comment by doublestranded** [comment]
- Fix distance calculation bug where stop is before geometry and is not getting zero distance.
- Add stop points to geometry if stops appear before or after geometry?
- Change precision of distances to whole meters or tenth of meters
