### ISSUE TITLE
Changeset::Error: PG::ProgramLimitExceeded: ERROR:  index row size 2944 exceeds maximum 2712 for index "index_current_route_stop_patterns_on_identifiers"

### ISSUE THREAD

**Issue by drewda** [transitland/transitland-datastore#355]
when I tried to import the Portland TriMet feed on staging last night, I got this error:

```
Changeset::Error: PG::ProgramLimitExceeded: ERROR:  index row size 2944 exceeds maximum 2712 for index "index_current_route_stop_patterns_on_identifiers"
HINT:  Values larger than 1/3 of a buffer page cannot be indexed.
Consider a function index of an MD5 hash of the value, or use full text indexing.
: INSERT INTO "current_route_stop_patterns" ("onestop_id", "stop_pattern", "trips", "geometry", "tags", "version", "created_or_updated_in_changeset_id", "route_id", "identifiers", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11) RETURNING "id" /*application:TransitlandDatastore,line:/app/models/concerns/current_tracked_by_changeset.rb:55:in `block in create_making_history'*/
```

@doublestranded, to fix this, I recommend switching the index from `btree` to `gin`. That's how we're indexing the other identifier array columns. For example, https://github.com/transitland/transitland-datastore/blob/7008fe98cfe1d48440cbfa985acf90579322f174/db/migrate/20150501181034_change_to_uri_style_identifiers.rb#L12

**Comment by doublestranded** [comment]
Is it ok to add "using: :gin" to the original migration or should I create another migration removing the identifier column and adding it back it with the new index type? "update_index" doesn't exist in rails migrations according to my knowledge.
