### ISSUE TITLE
FeedFetch and FeedInfo services aren't handling GTFS archives hosted on GitHub

### ISSUE THREAD

**Issue by drewda** [transitland/transitland-datastore#407]
Perhaps an issue with `Content-Type` headers?

Will https://rawgit.com/ help?

**Comment by barbeau** [comment]
Using rawgit:
https://rawgit.com/CUTR-at-USF/bullrunner-gtfs-realtime-generator/master/bullrunner-gtfs.zip

I get error:

>THERE WAS AN ERROR DOWNLOADING THE FILE. THE TRANSIT OPERATOR SERVER RESPONDED WITH: 400 "BAD REQUEST".

**Comment by irees** [comment]
Our http handler may not work well with redirect-to-https. I'm looking into using a libcurl-based fetcher, e.g. curb https://github.com/taf2/curb

**Comment by barbeau** [comment]
@drewda Is this fix live?  Just tried again and I'm still getting the generic "problem downloading" using the Github URL:
https://github.com/CUTR-at-USF/bullrunner-gtfs-realtime-generator/raw/master/bullrunner-gtfs.zip

I haven't tried the rawgit.com URL.

**Comment by drewda** [comment]
@barbeau we're testing on our development server today. We'll follow up when the fix is on the production servers.

**Comment by barbeau** [comment]
@drewda Ok, thanks!

**Comment by drewda** [comment]
@barbeau the fix is now live, so you can retry whenever.

We still will need to address https://github.com/transitland/transitland-datastore/issues/408 before this feed can be fully imported (we have some open questions about how to best represent frequency-based schedules for routing purposes). But it should still be possible to add the feed and its operator record to the Feed Registry in the meantime.

**Comment by barbeau** [comment]
@drewda Thanks, just submitted successfully!  

Yeah, true frequency-based trips (`exact_times=0`) are tricky for routing and real-time.  Happy to discuss this further based on our experience if it helps - we did some prototyping in OpenTripPlanner for supporting `exact_times=0` real-time (https://github.com/opentripplanner/OpenTripPlanner/pull/1647), and also created a GTFS-realtime feed for the USF Bull Runner (https://github.com/CUTR-at-USF/bullrunner-gtfs-realtime-generator).

**Comment by drewda** [comment]
@barbeau great, glad to hear the submission succeed! We just applied the changeset (https://transit.land/dispatcher/changesets/598), and it's now listed at https://transit.land/feed-registry/operators/o-dhvrs-usfbullrunner

Unclear when we'll be ready to tackle frequency-based routing, but you're welcome to offer any thoughts under #408 in the meantime.

**Comment by barbeau** [comment]
@drewda Thanks!  Just commented in #408 with the same above info, and I'll track the issue there.
