### ISSUE TITLE
Some problems with API endpoint

### ISSUE THREAD

**Issue by aborruso** [transitland/transitland-datastore#416]
Dear all,
I have seen you have added a GTFS of my country (Rome, Italy) in the feed registry, but I have no result using the API endpoint.

I have made these two requests:
- [https://transit.land/api/v1/routes?bbox=1,1,80,80](https://transit.land/api/v1/routes?bbox=1,1,80,80)
- [https://transit.land/api/v1/routes?operatedBy=o-sr2-romaserviziperlamobilitsrl](https://transit.land/api/v1/routes?operatedBy=o-sr2-romaserviziperlamobilitsrl)

I have always an empy result. What's wrong in my requests?

Thank you

**Comment by drewda** [comment]
Hi @aborruso, thanks for your submission and for writing to us! We applied the changeset to create the Rome feed and operator models. But we have not yet run an import process to create stops, routes, and schedule data for the Rome feed. We spread out the initial imports over a couple days, so we're able to make sure they complete successfully. We'll import the Rome feed soon and let you know when it's ready.

**Comment by aborruso** [comment]
On 15 February 2016 at 16:19, Drew Dara-Abrams <notifications@github.com>
wrote:

> Hi @aborruso <https://github.com/aborruso>, thanks for your submission
> and for writing to us! We applied the changeset to create the Rome feed and
> operator models. But we have not yet run an import process to create stops,
> routes, and schedule data for the Rome feed. We spread out the initial
> imports over a couple days, so we're able to make sure they complete
> successfully. We'll import the Rome feed soon and let you know when it's
> ready.
>

You are very kind, thank you very much


-- 
 Andrea Borruso
website: http://blog.spaziogis.it
GEO+ geomatica in Italia http://bit.ly/GEOplus
38° 7' 48" N, 13° 21' 9" E, EPSG:4326

--

"cercare e saper riconoscere chi e cosa,
 in mezzo all’inferno, non è inferno,
e farlo durare, e dargli spazio"

Italo Calvino

**Comment by aborruso** [comment]
Hi @drewda this is only a proposal, it is not a criticism: I think it would be better to put in list a new data source only when the import process will be complete.

Thansitland is really a great idea/product

**Comment by drewda** [comment]
Thanks for the feedback, and glad you're liking Transitland. We're still figuring out how to best scale and manage the contribution process.

**Comment by drewda** [comment]
@aborruso we've now fully imported the routes, stops, and schedule data for the Rome feed.

Here are some example queries that are now possible:

- https://transit.land/api/v1/routes?operatedBy=o-sr2-romaserviziperlamobilitsrl
- https://transit.land/api/v1/stops?servedBy=o-sr2-romaserviziperlamobilitsrl

Yes, that's a good idea to better indicate where in the import process a feed is. In the future, we'll be adding an activity feed (https://github.com/transitland/transitland-datastore/issues/395) and perhaps also better visual indicators on the Feed Registry to show what level of data is available for each feed.

Thanks again for your participation!

**Comment by aborruso** [comment]
Thank you very much @drewda 

In these days I have submitted other 2 importants GTFS files (for Napoli, Italy). If these will be ready for 5 March, the [open data day](http://opendataday.org/), I think that coud be used for a local hackathon.
It's only a desire, I do not want you to hurry.

Best regards

**Comment by drewda** [comment]
@aborruso you're welcome. We'd love to equip you and your colleagues for the hackathon--we'll see about getting those feeds imported soon.

It's less useful than the feeds, but we can also mail you some Transitland stickers if you'd like! If so, just e-mail us your mailing address to transitland@mapzen.com

**Comment by aborruso** [comment]
Thank you @drewda I have sent an email for the stickers.

And now I pray for the feed :)

**Comment by drewda** [comment]
@aborruso stickers are in the mail, and the feeds are imported.

Please have a look through the Transitland Playground and API. Let us know if you see any problems, or if it's all set to help at your hackathon.

And in any case, if your hackathon produces any interesting apps, visualizations, or analyses using the Transitland API, please let us know. We'd love a guest blog post, a tweet of a screenshot, or whatever you and your collaborators would like to share!

**Comment by aborruso** [comment]
Dear Drew,
first of all thank you very much.

On 1 March 2016 at 19:10, Drew Dara-Abrams <notifications@github.com> wrote:

> @aborruso <https://github.com/aborruso> stickers are in the mail, and the
> feeds are imported.
>
> Please have a look through the Transitland Playground and API. Let us know
> if you see any problems, or if it's all set to help at your hackathon.
>
I have seen yesterday and your API is fantastic.

> And in any case, if your hackathon produces any interesting apps,
> visualizations, or analyses using the Transitland API, please let us know.
> We'd love a guest blog post, a tweet of a screenshot, or whatever you and
> your collaborators would like to share!
>

I hope that Transitland API will produce some good result, but I can not be
sure, because developers have been informed today, but if not it will for
Open Data Day, now all civic hackers, developers and citizems have a new
powerful tool available,  that will help them build great things.

I will inform you about our results.

Thank you very much




-- 
 Andrea Borruso
website: http://blog.spaziogis.it
GEO+ geomatica in Italia http://bit.ly/GEOplus
38° 7' 48" N, 13° 21' 9" E, EPSG:4326

--

"cercare e saper riconoscere chi e cosa,
 in mezzo all’inferno, non è inferno,
e farlo durare, e dargli spazio"

Italo Calvino

**Comment by drewda** [comment]
You're welcome, @aborruso. My colleagues and I all appreciate your interest and enthusiasm.
