### ISSUE TITLE
Profiling and benchmarking of RSP generation process (and FeedEater)

### ISSUE THREAD

**Issue by doublestranded** [transitland/transitland-datastore#469]

**Comment by doublestranded** [comment]
Need to use Ruby Interpreter patch for memory profiling in ruby-prof

**Comment by drewda** [comment]
@doublestranded working on this with @baldur, writing notes at https://github.com/transitland/transitland-datastore/blob/master/doc/profiling.md

**Comment by doublestranded** [comment]
Idea: run different-sizes GTFS imports and plot total memory usage (breakdown by file/component (RouteStopPattern, Stop, etc).
