### ISSUE TITLE
Query starting from two stops

### ISSUE THREAD

**Issue by aborruso** [transitland/transitland-datastore#487]
Dear all,
is it possible to query transiland API, starting from two bus stops of a network, to have all the possible routes that I can choose to go from A to B along the same network.

Thank you very much,

Andrea

**Comment by drewda** [comment]
@aborruso using the Transitland Datastore schedule API endpoints, you can query for all the trips that leave one or more stops. For example, this query shows all trips departing from two different train stations here in San Francisco: https://transit.land/api/v1/schedule_stop_pairs?origin_onestop_id=s-9q8yyv42k3-caltrain~sanfranciscostation,s-9q8yycsdkr-caltrain~22ndststation

If you want to calculate a route that traverses multiple stops, you'll need a separate routing engine. The Datastore API provides all the schedule data necessary to power a routing engine, but it does not itself plan journeys.

**Comment by aborruso** [comment]
Thank you
