### ISSUE TITLE
improve API queries for route color

### ISSUE THREAD

**Issue by drewda** [transitland/transitland-datastore#514]
- [x] allow users to query API for all routes that have a color defined: `/api/v1/routes?color=true` (should use the `color` attribute on the `Route` model, rather than the tag)
- [x] allow users to query API for all routes with a specific color `/api/v1/routes?color=FFFFFF` (should use the `color` attribute on the `Route` model, rather than the tag) <-- **I see this is already supported**
- [ ] consider adding `text_color` attribute to `Route` model (along with appropriate API query options)
- [ ] add specs to cover RoutesController additions
- [ ] no longer populate `route_color` in tags in `Route.from_gtfs()`
- [ ] clear out existing `route_color` values from route tags on production

This is to help @IndyHurt with some queries for her upcoming blog post.

Also worth checking with @gknisely to make sure that they're ingesting the `color` model attribute on `Route`, rather than the tag values.

**Comment by gknisely** [comment]
We do use tags.route_color and tags.route_text_color from the Routes.   @drewda when is this change happening.

**Comment by drewda** [comment]
@gknisely we already populate the `color` attribute on the Route model. (It should always equal the value of `tags[route_color]`). So you can switch over to using that any time.

I hadn't realized you were also making use of `tags[text_color]`. Maybe we should migrate that to a model-level attribute, too.

In any case, we can continue with the duplication between model-level attributes and tag values until you're ready to migrate. I just want to make sure that we're consistent before we start building editing tools next month.

**Comment by gknisely** [comment]
@drewda once you figure out text_color, let me know as this should be a 2 minute update on our side and 10 minutes to test.  If all good, we can then both release the updates.  Let me know.  

--Greg.
