### ISSUE TITLE
before RSP launch, clear out any duplicate or outdated RSPs

### ISSUE THREAD

**Issue by drewda** [transitland/transitland-datastore#526]
`RAILS_ENV=production ./bin/bundle exec rake db:cleanup:cleanup_unreferenced_e...`

**Comment by drewda** [comment]
`RAILS_ENV=production ./bin/bundle exec rake db:cleanup:cleanup_unreferenced_entities`
produces a much longer list than I expected: 
https://gist.github.com/drewda/a0f03fe1cfd62cd55724925f7d98b475

**Comment by irees** [comment]
Closing this issue; deeper debugging now in #561
