### ISSUE TITLE
Timezone is not set for some stops in Transitland

### ISSUE THREAD

**Issue by gknisely** [transitland/transitland-datastore#528]
Stop time_zones should always be set; however, some are not in Transitland.  Based on the GTFS spec, if the optional time_zone field is not populated for the stop, you should use the required time_zone field from the agency file.

From the spec:

agency_timezone     Required	
The agency_timezone field contains the timezone where the transit agency is located. Timezone names never contain the space character but may contain an underscore. Please refer to http://en.wikipedia.org/wiki/List_of_tz_zones for a list of valid values. If multiple agencies are specified in the feed, each must have the same agency_timezone.

stop_timezone     Optional
The stop_timezone field contains the timezone in which this stop or station is located. Please refer to Wikipedia List of Timezones for a list of valid values. If omitted, the stop should be assumed to be located in the timezone specified by agency_timezone in agency.txt.

Errors from fetcher:

2016/03/23 21:39:16.172599 [WARN] Timezone not found for stop Western/37th SE corner
2016/03/23 21:39:16.172637 [WARN] Timezone not found for stop Western/33rd SE corner
2016/03/23 21:39:16.172675 [WARN] Timezone not found for stop 41st/Western NE corner
2016/03/23 21:39:16.172713 [WARN] Timezone not found for stop 41st/Holly NE corner
2016/03/23 21:39:16.172751 [WARN] Timezone not found for stop 41st/Kiwanis NE corner
2016/03/23 21:39:16.172789 [WARN] Timezone not found for stop 41st/O'Gorman entrance
2016/03/23 21:39:16.172828 [WARN] Timezone not found for stop 47th/Louise SE corner
2016/03/23 21:39:16.172865 [WARN] Timezone not found for stop Louise at Target entrance driveway NE corner
2016/03/23 21:39:16.172903 [WARN] Timezone not found for stop 41st/Westport SW corner
2016/03/23 21:39:16.172940 [WARN] Timezone not found for stop 41st/adjacent to (east of) Big Sioux River
2016/03/23 21:39:16.172976 [WARN] Timezone not found for stop 41st/Kiwanis – SW Corner
2016/03/23 21:39:16.173013 [WARN] Timezone not found for stop 41st/Elmwood SW corner
2016/03/23 21:39:16.173049 [WARN] Timezone not found for stop 41st/Western SW corner

Thanks.

--Greg.

**Comment by irees** [comment]
Might have been a transient issue: all Stops on production have timezones. However, I will make timezone a required attribute.

For amusement, here are the current timezones in 212952 stops:
Africa/Nairobi
America/Anchorage
America/Argentina/Buenos_Aires
America/Boise
America/Chicago
America/Denver
America/Detroit
America/Kentucky/Louisville
America/Los_Angeles
America/Mexico_City
America/Montreal
America/New_York
America/Phoenix
America/Tijuana
America/Vancouver
Australia/Brisbane
Europe/Rome
US/Central
