### ISSUE TITLE
edit "stickiness"

### ISSUE THREAD

**Issue by drewda** [transitland/transitland-datastore#570]
idea under consideration: every entity has a `sticky_attrs_and_tags` array that lists (as string) which attributes and tags are protected because they've been edited by a user-created changeset

For example: editing the name of a stop will mark `name` as a "sticky" attribute, not for automatic updating when a feed is reimported by FeedEater.

related to #569 and #332

**Comment by doublestranded** [comment]
Conditions:
1) first import must save data
2) “manual” changesets write over data
3) subsequent imports do not write over data

**Comment by doublestranded** [comment]
Make sure quality checks (and issue generation) is done *after* sticky attributes has been enforced.

**Comment by doublestranded** [comment]
Make sure the Dispatcher's edit changesets only include the attributes that are changed. This will require #684
