### ISSUE TITLE
RouteStopPattern creation error in `f-dpmg-rta`

### ISSUE THREAD

**Issue by drewda** [transitland/transitland-datastore#573]
On re-importing newer versions of the `f-dpmg-rta` feed fail with the following error

>
{:exception_log=>"\nNeed at least two stops\n[\"/srv/www/transitland/releases/20160418192402/app/models/route_stop_pattern.rb:325:in `create_from_gtfs'\", \"/srv/www/transitland/releases/20160418192402/app/services/gtfs_graph.rb:305:in `block in load_tl_route_stop_patterns'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/bundler/gems/gtfs-d4e155a65875/lib/gtfs/source.rb:278:in `block in trip_stop_times'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/bundler/gems/gtfs-d4e155a65875/lib/gtfs/source.rb:275:in `each'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/bundler/gems/gtfs-d4e155a65875/lib/gtfs/source.rb:275:in `trip_stop_times'\", \"/srv/www/transitland/releases/20160418192402/app/services/gtfs_graph.rb:294:in `load_tl_route_stop_patterns'\", \"/srv/www/transitland/releases/20160418192402/app/services/gtfs_graph.rb:32:in `create_change_osr'\", \"/srv/www/transitland/releases/20160418192402/app/workers/feed_eater_worker.rb:47:in `perform'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.1/lib/sidekiq/processor.rb:151:in `execute_job'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.1/lib/sidekiq/processor.rb:133:in `block (2 levels) in process'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.1/lib/sidekiq/middleware/chain.rb:127:in `block in invoke'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-unique-jobs-4.0.17/lib/sidekiq_unique_jobs/lock/until_and_while_executing.rb:8:in `block in execute'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-unique-jobs-4.0.17/lib/sidekiq_unique_jobs/lock/while_executing.rb:19:in `synchronize'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-unique-jobs-4.0.17/lib/sidekiq_unique_jobs/lock/until_and_while_executing.rb:6:in `execute'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-unique-jobs-4.0.17/lib/sidekiq_unique_jobs/server/middleware.rb:16:in `call'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.1/lib/sidekiq/middleware/server/active_record.rb:6:in `call'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.1/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.1/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.1/lib/sidekiq/logging.rb:31:in `with_context'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.1/lib/sidekiq/middleware/server/logging.rb:7:in `call'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.1/lib/sidekiq/middleware/chain.rb:132:in `call'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.1/lib/sidekiq/middleware/chain.rb:132:in `invoke'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.1/lib/sidekiq/processor.rb:128:in `block in process'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.1/lib/sidekiq/processor.rb:167:in `stats'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.1/lib/sidekiq/processor.rb:127:in `process'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.1/lib/sidekiq/processor.rb:79:in `process_one'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.1/lib/sidekiq/processor.rb:67:in `run'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.1/lib/sidekiq/util.rb:16:in `watchdog'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.1/lib/sidekiq/util.rb:24:in `block in safe_thread'\"]\n"}

Copied from https://transit.land/dispatcher/feeds/f-dpmg-rta

**Comment by doublestranded** [comment]
Looks like the feed contains (15) trips with only one stop time:

From feedvalidator.py:
The trip with the trip_id "13953758-1603RS-hr1603a6-Saturday-20" only has one stop on it; it should have at least one more stop so that the riders can leave!

 and this is raising an error as was originally intended; however since trips with no stop times are already ignored (stop times for a trip is not a strict requirement by the spec or validator) trips with only one stop time should be ignored as well. Working on a fix.
