### ISSUE TITLE
Method Geometry#convex_hull not defined.

### ISSUE THREAD

**Issue by jbpin** [transitland/transitland-datastore#614]
I try to import a GTFS feed then when creating the operator I got this issue.

```Method Geometry#convex_hull not defined.```

I think is due to Rgeo lib.. since Geometry#convex_hull is define [here](https://github.com/rgeo/rgeo/blob/master/lib/rgeo/feature/geometry.rb#L455)

```
def convex_hull
    raise Error::UnsupportedOperation, "Method Geometry#convex_hull not defined."
end
```

Any idea ?

**Comment by drewda** [comment]
This is usually a sign that RGeo is not properly bound to the native GEOS library.

In a Rails console, try:

```rb
RGeo::Geos.supported?
```

More information on which version of GEOS to install at https://github.com/rgeo/rgeo#dependencies

If this doesn't solve your problem, please reopen the issue and let us know what you encountered!
