### ISSUE TITLE
in Stop, StopStation, and StopPlatform list the vehicle_types that serve it

### ISSUE THREAD

**Issue by drewda** [transitland/transitland-datastore#632]
- [x] finder methods on Stop model with the ActiveRecord query
- [x] list in Stop, StopStation, and StopPlatform serializers
- [x] query param in StopsController that allows searching by, say, `served_by_vehicle_types`

**Comment by irees** [comment]
- [ ] Add vehicle_type integer/string conversion (and mixed) to GTFS wrapper
