### ISSUE TITLE
FeedVersion descriptive stats

### ISSUE THREAD

**Issue by drewda** [transitland/transitland-datastore#646]
Right now, when a new FeedVersion is fetched and created, we extract and store some simple descriptive info in tags (first calendar date, last calendar date, feed_info contents, etc.) For example: http://transit.land/api/v1/feed_versions?sha1=dd7aca4a8e4c90908fd3603c097fabee75fea907

In the future, let's use the FeedFetch process and the FeedVersion model as the time and place to compute out more descriptive stats about a GTFS feed. Possibilities that we have already talked about:

- `#` of stops, routes, and other entities
- `#` of trips
- % of trips that are frequency-based
- distribution of trips throughout the calendar range (data to power a histogram)
- ...

The two goals would be to store enough information to make it easy to decide whether to import a new FeedVersion and for overall analysis of trends in GTFS style.

**Comment by drewda** [comment]
@barbeau we can use this ticket to collect more ideas about analytics to collect on each feed version

**Comment by barbeau** [comment]
After thinking about this more, here are the types of questions that I'd like to see Transitland be able to answer, stated more abstractly:

1. How many agencies are providing optional field X?
1. How are agencies using field X (i.e., pull back values for this field for all agencies)?
1. How are agencies using field X as compared to field Y (i.e., pull back values for more than one field for all agencies?
1. How many records existing for each table for each agency?

Concrete examples of each of the above:

1. How many agencies are providing the `stops.wheelchair_boarding` field in their data?
1. What are all the characters being used in `stops.stop_ids` (or any other field ID)?
1. What text are agencies using for `trips.trip_headsign` vs `trips.trip_short_name`?
1. What is the average number of records included in `shapes.txt`?

Purpose behind 1 and 4 are to get a sense if a particular agency is an outlier (e.g., seeing if building a new feature around wheelchair_boardings is worth the work given the number of providers with data, or seeing if an agency is including "too many" shape points), and 2 and 3 are for an app developer to get a better idea of how to handle data in their app (e.g., writing a unit test to make sure all characters are being handled properly, seeing how a particular field may appear in their UI when generalizing to all agencies).

So ideally I think it's not just stats, but also being able to inspect the data itself (an expansion of Playground).

**Comment by barbeau** [comment]
On a related note - I think a simple UI status dashboard that shows all of the agencies in Transitland and whether or not their GTFS is currently valid (red/green badge) would be helpful as well.  We're currently dealing with MARTA in Atlanta allowing their GTFS to expire:
https://groups.google.com/forum/#!topic/atl-transit-developers/dRPeapi8lyA

Having a dashboard showing (almost) everyone else green and MARTA red would be a great tool to show MARTA management - hopefully this would encourage them to be like other agencies.

**Comment by irees** [comment]
Concept:

```{
  "version": 1.0,
  "stops.txt": {
    "count": 100,
    "stop_id": 100,
    "stop_name": 90
  },
  "trips.txt": {
    "count": 100,
    "trip_id": 100,
    "block_id": 5
  },
  "frequencies.txt": {
    "count": 10,
    "trip_id": 10
  }
  "service_hours_histogram": {
    "2017-015": 2000,
    "2017-016": 2000,
    "2017-017": 100
  }
  "filenames": ["stops.txt", "README.txt"]
}```

Include basic stats for each GTFS csv file, including row count, columns, and the number of populated values per column. Additionally, calculate total service hours for each week from the calendar start to end. Also include all a list of all filenames in the archive.

**Comment by irees** [comment]
Current proposal... stats generated for Caltrain.

https://gist.github.com/irees/b01137f18d9e64830f1b6e358b3c0f93

**Comment by irees** [comment]
Updated proposal.

https://gist.github.com/irees/054c58906003c292e6493ca739d150a4

**Comment by irees** [comment]
example: http://dev.transit.land/api/v1/feed_version_infos/1
