### ISSUE TITLE
SSP 'where_active' performance

### ISSUE THREAD

**Issue by irees** [transitland/transitland-datastore#657]
Check performance of where_active, especially as the number of Feeds increases.

**Comment by drewda** [comment]
Notes on some database performance options worth potentially trying:

- try replacing some B-tree indices with GIN. (Sounds like compound GIN indices can be used in many permutations, unlike B-tree indices: https://www.postgresql.org/message-id/D599302A-50E6-4758-856E-61D619F4434F@gmail.com )
- read more about BRIN indices and consider whether useful given the ordering and grouping of rows in `current_schedule_stop_pairs` table: https://www.postgresql.org/docs/9.5/static/brin-intro.html and http://pythonsweetness.tumblr.com/post/119568339102/block-range-brin-indexes-in-postgresql-95
- `CLUSTER` the `current_schedule_stop_pairs` table along an index: https://www.postgresql.org/docs/current/static/sql-cluster.html

I'll check in with Matt A. and Rob to see if either of them can help with some experiments.

**Comment by drewda** [comment]
Also, as we chatted about on and off, we could reconsider the use of the "active" flag. Perhaps we should consider all rows in `current_schedule_stop_pairs` to be active and use a different "work" table for SSP imports in progress?

In any case, some ideas to mull over while looking for shorter-term index or query improvements.

**Comment by irees** [comment]
Ideas:
- Disable `where_active` default scope
- Delete old SSPs (FeedEaterScheduleDeleterWorker?)
- Run benchmarks on `where_active` and FESDW

**Comment by drewda** [comment]
I'll chat with Grant about having Pingdom monitor the default SSP query endpoint

**Comment by drewda** [comment]
Related change on transit fetcher side: https://github.com/valhalla/mjolnir/pull/500

**Comment by irees** [comment]
Fix is now on production. http://transit.land/api/v1/schedule_stop_pairs
