### ISSUE TITLE
Forth Worth & other feeds: Changeset::Error Couldn't find Stop

### ISSUE THREAD

**Issue by doublestranded** [transitland/transitland-datastore#660]
Feed import error with Forth Worth (f-9vff-fortworthtransportationauthority) and Oslo region (f-u4-ruter~flybussen~Østfoldkollektivtrafikk~hedmarktrafikk~oppl). 

Exception log:

{:exception_log=>"\nChangeset::Error Couldn't find Stop\n[\"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/core.rb:196:in `find_by!'\", \"/srv/www/transitland/releases/20160706053807/app/models/concerns/has_a_onestop_id.rb:10:in `find_by_onestop_id!'\", \"/srv/www/transitland/releases/20160706053807/app/models/stop.rb:304:in `block in update_includes_stop_transfers'\", \"/srv/www/transitland/releases/20160706053807/app/models/stop.rb:303:in `each'\", \"/srv/www/transitland/releases/20160706053807/app/models/stop.rb:303:in `update_includes_stop_transfers'\", \"/srv/www/transitland/releases/20160706053807/app/models/stop.rb:92:in `after_create_making_history'\", \"/srv/www/transitland/releases/20160706053807/app/models/concerns/current_tracked_by_changeset.rb:46:in `block in apply_changes_create_update'\", \"/srv/www/transitland/releases/20160706053807/app/models/concerns/current_tracked_by_changeset.rb:46:in `each'\", \"/srv/www/transitland/releases/20160706053807/app/models/concerns/current_tracked_by_changeset.rb:46:in `apply_changes_create_update'\", \"/srv/www/transitland/releases/20160706053807/app/models/concerns/current_tracked_by_changeset.rb:24:in `apply_changes'\", \"/srv/www/transitland/releases/20160706053807/app/models/change_payload.rb:75:in `block in apply!'\", \"/srv/www/transitland/releases/20160706053807/app/models/change_payload.rb:72:in `<<'\", \"/srv/www/transitland/releases/20160706053807/app/models/change_payload.rb:72:in `each'\", \"/srv/www/transitland/releases/20160706053807/app/models/change_payload.rb:72:in `each'\", \"/srv/www/transitland/releases/20160706053807/app/models/change_payload.rb:72:in `apply!'\", \"/srv/www/transitland/releases/20160706053807/app/models/changeset.rb:195:in `block (2 levels) in apply!'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/relation/delegation.rb:46:in `each'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/relation/delegation.rb:46:in `each'\", \"/srv/www/transitland/releases/20160706053807/app/models/changeset.rb:194:in `block in apply!'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/transactions.rb:220:in `transaction'\", \"/srv/www/transitland/releases/20160706053807/app/models/changeset.rb:192:in `apply!'\", \"/srv/www/transitland/releases/20160706053807/app/services/gtfs_graph.rb:100:in `create_change_osr'\", \"/srv/www/transitland/releases/20160706053807/app/workers/feed_eater_worker.rb:47:in `perform'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/processor.rb:152:in `execute_job'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/processor.rb:134:in `block (2 levels) in process'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-unique-jobs-4.0.17/lib/sidekiq_unique_jobs/lock/until_and_while_executing.rb:8:in `block in execute'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-unique-jobs-4.0.17/lib/sidekiq_unique_jobs/lock/while_executing.rb:19:in `synchronize'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-unique-jobs-4.0.17/lib/sidekiq_unique_jobs/lock/until_and_while_executing.rb:6:in `execute'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-unique-jobs-4.0.17/lib/sidekiq_unique_jobs/server/middleware.rb:16:in `call'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/middleware/server/active_record.rb:6:in `call'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/logging.rb:32:in `with_context'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/middleware/server/logging.rb:7:in `call'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/middleware/chain.rb:133:in `call'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/middleware/chain.rb:133:in `invoke'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/processor.rb:129:in `block in process'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/processor.rb:168:in `stats'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/processor.rb:128:in `process'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/processor.rb:80:in `process_one'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/processor.rb:68:in `run'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/util.rb:17:in `watchdog'\", \"/home/deploy/.bundler/transitland/ruby/2.2.0/gems/sidekiq-4.1.2/lib/sidekiq/util.rb:25:in `block in safe_thread'\"]\n"}

**Comment by irees** [comment]
Resolved by #661

**Comment by drewda** [comment]
Longer term fix will be #667
