### ISSUE TITLE
include only one geometry for each route on routes endpoint

### ISSUE THREAD

**Issue by drewda** [transitland/transitland-datastore#671]
@doublestranded I'm creating this issue as a note for the future. Not urgent, but @meghanhade's work on the Mobility Explorer is revealing how route queries are somewhat slow in comparison with other queries.

---

The `/routes` API endpoint is somewhat slow because it returns MultiLineString geometries that combine all possible RSP geometries for each route. The lines are also often redundant when overlaid on a map.

In the future, let's consider returning only a single geometry for each route. (Maybe even force it to be a LineString?) If API users want all the possible geometries for a route, they can query the `/route_stop_patterns` endpoint with appropriate filters.

Two possible options:
- Designate one RSP as the "canonical" geometry one that gets returned by default. This could be decided automatically with a simple heuristic. And when necessary, it could be switched from one RSP to another manually using the Dispatcher admin interface. (related to https://github.com/transitland/dispatcher/issues/59 )
- Construct a "composite" geometry for a route that combines together all the RSP geometries and then removes redundant segments that overlap.

**Comment by doublestranded** [comment]
I can think of several possibilities to do this:

1) Look at unique trip headsigns (or stop time headsigns) and pick a representative Route Stop Pattern from those groups.

2) Use a metric like Hausdorff distance (already provided in PostGIS) to compare the similarity between two polylines. The difficulty in this comes from somehow clustering the comparisons to get a representive polyline from each group.

3) Reconsider breaking Route Stop Pattern further into stop pair paths. This would ensure the whole route is covered while minimizing duplication (although it's possible to have two distinct stop pair paths based on different geometries between them). It would also make editing easier in some ways. 

It almost goes without saying, but these operations would have to be done during import or update of computed attributes, and stored ready to go with the route.

**Comment by drewda** [comment]
@doublestranded sounds like great options to keep in mind while you're working on geometry editing tools.

When you're ready to tackle this, let me know so we can chat about how to take into account the needs of Mobility Explorer and other API users.

**Comment by doublestranded** [comment]
- []  add to computed properties
