### ISSUE TITLE
aggregate `wheelchair_accessible` and `bikes_allowed` on `Route` model

### ISSUE THREAD

**Issue by drewda** [transitland/transitland-datastore#672]
`ScheduleStopPair`s include information on whether that trip is accessible to wheelchairs and whether bikes are allowed onboard. (The two "nullable" booleans are populated by FeedEater from `trips.txt` in GTFS feeds.)

It would be helpful to be able to view and query these two properties at the route level. Important for Mobility Explorer (cc @meghanhade) as well as other types of analysis when you don't want to have to query through all possible SSPs.

TODO:
- [x] add two more attributes to `Route` model. Probably have them as string enums:
    - `wheelchair_accessible`: {"some_trips","all_trips","no_trips","unknown"}
    - `bikes_allowed`: {"some_trips","all_trips","no_trips","unknown"}
- [x] Populate attributes via `trips.txt` in FeedEater level 1
- [x] Editable via changeset
- [ ] allow filtering by query param on `/routes` API endpoint

Future work:
- [ ] have callbacks on `ScheduleStopPair` creation update those attributes on associated `Route` model, or use "computed property"

**Comment by irees** [comment]
Consider how GTFS stop "wheelchair_boarding" interacts with Route wheelchair_accessible / bikes_allowed
