### ISSUE TITLE
automatically removed outdated ScheduleStopPairs after feed re-imports (and delete any outdated SSPs currently in database)

### ISSUE THREAD

**Issue by drewda** [transitland/transitland-datastore#690]
Now that we're not filtering ScheduleStopPairs to only show SSPs from "active feeds" by default (changed by #679), we should be removing out of date SSPs automatically. This will also keep the database slightly smaller, so we can save space for new feeds (rather than additional versions of existing feeds).

TODO:
- [x] async job to remove outdated SSPs that can run after a feed re-import completes
- [x] enqueue FeedDeactivationWorkers from console to clear out old SSPs

**Comment by irees** [comment]
To clear out old FeedVersion SSPs:

```
# find non-active FeedVersions
fvs = FeedVersion.all.select { |fv| !fv.is_active_feed_version}
# verify
fvs.map(&:is_active_feed_version).uniq
# enqueue deactivation workers
fvs.each { |fv| FeedDeactivationWorker.perform_async(fv.feed.onestop_id, fv.sha1) }
```

**Comment by irees** [comment]
Went from about 230m SSPs to 94m
