### ISSUE TITLE
Operator: update convex hull as computed property

### ISSUE THREAD

**Issue by irees** [transitland/transitland-datastore#704]
Currently, GTFSGraph updates the convex hull of Operators based on the GTFS stops associated with the GTFS agency. However, this fails when an agency has no routes/trips/stops.

However, Stops created/edited through changesets don't update the Operator convex hull.

- [x] Changeset callback to update Operator geometry whenever a Stop is edited

**Comment by drewda** [comment]
This functionality was added by https://github.com/transitland/transitland-datastore/pull/655
