### ISSUE TITLE
if an operator only has two stops, its convex hull is a LineString rather than a Polygon

### ISSUE THREAD

**Issue by drewda** [transitland/transitland-datastore#714]
This problem first came up with the NYC DOT, which operates the Staten Island Ferry (https://transit.land/feed-registry/operators/o-dr5r7-nycdot). It only has two stops, at the ends of the ferry route; its operator geometry (convex hull) has been computed as a LineString with just two points. This makes it complicated to parse client-side, if you're not guaranteed a polygon.

For the time being, we're manually edited the operator geometry to be a polygon: https://transit.land/dispatcher/changesets/2108

In the future, let's look into adding a buffer around stops so that an operator with only two stops gets a polygon.

Timeframe: Not urgent.

**Comment by doublestranded** [comment]
factory = RGeo::Cartesian.factory(
  srid: 4326, buffer_resolution: 8
)
line = factory.line_string([factory.point(1,2),factory.point(2,2])
line.buffer(0.5)
