### ISSUE TITLE
Changeset::Error errors to array

### ISSUE THREAD

**Issue by doublestranded** [transitland/transitland-datastore#730]
Ember Data needs "errors" as array instead of object.

**Comment by drewda** [comment]
One place where the object/hash will change into an array: https://github.com/transitland/transitland-datastore/blob/master/app/controllers/api/v1/base_api_controller.rb#L65-L70

**Comment by drewda** [comment]
Let's test this on dev servers first to make sure that it doesn't break any other Dispatcher functionality. For example, the way @irees is checking for changeset application errors in Dispatcher.

**Comment by doublestranded** [comment]
This change is unnecessary for now; will use async changeset from #732
