### ISSUE TITLE
OperatorsInFeed: Operator referenced by multiple gtfs agency_id's

### ISSUE THREAD

**Issue by irees** [transitland/transitland-datastore#735]
Each feed can only reference an operator once, using `OperatorsInFeed`.

To support feeds like https://github.com/transitland/transitland/issues/81, that have multiple gtfs `agency_id`s referencing a single Operator onestop_id, we may want to remove this constraint.

However, it will make updating `OperatorsInFeed` `gtfs_agency_id` a bit trickier; first, add the new gtfs `agency_id` through `includesOperators`, then remove the old one through `doesNotIncludeOperators`.

**Comment by stevevance** [comment]
Is there any progress on this?
It does affect an open issue about [a feed in Finland](https://github.com/transitland/transitland/issues/81).

**Comment by drewda** [comment]
@irees has this in a testing state on his own machine, but it's a large enough change that we'll all need to do a bit more testing before merging it out to servers. Given the number of other code changes in the works right now, I think it will likely have to wait until the week after next.
