### ISSUE TITLE
RSP Optimization 2

### ISSUE THREAD

**Issue by doublestranded** [transitland/transitland-datastore#748]
- [x] Experiment with how to generate and compare RSP onestop ids to entities in GTFSGraph
- [x] use profiler with #669 with other entities
- [x] add a comment in profile rake task about local testing and existing feeds

**Comment by doublestranded** [comment]
For future reference:  the profiler results show that memory is allocated heavily during RouteStopPattern's 'cartesian_cast' method and in generating the RouteStopPattern OnestopId (which also utilizes geometries).

**Comment by irees** [comment]
Substantial improvements in runtime performance were made, up to 75% in RSP loading. There may still be further improvements in the future.
