### ISSUE TITLE
Turn on automatic feed import and schedule extension

### ISSUE THREAD

**Issue by irees** [transitland/transitland-datastore#795]
Automatic feed imports (#745) and automatic feed extension (#784) tasks exist, and can be enabled with environment variables. Enable these jobs on dev, then prod.

- [x] dev: EXTEND_EXPIRED_FEED_VERSIONS=true
- [x] dev: ENQUEUE_NEXT_FEED_VERSIONS_MAX=10
- [x] prod: EXTEND_EXPIRED_FEED_VERSIONS=true
- [x] prod: ENQUEUE_NEXT_FEED_VERSIONS_MAX=10

**Comment by irees** [comment]
Working well on dev. Will turn on in prod after next deploy.

**Comment by drewda** [comment]
Before enabling on prod, I think it's important to finish #792 and #793 so you can monitor automatic feed extension through the activity feed in Slack and Dispatcher.

**Comment by irees** [comment]
Will do.
