### ISSUE TITLE
Operator delete: also remove OperatorInFeed records

### ISSUE THREAD

**Issue by irees** [transitland/transitland-datastore#807]
An old, deprecated Operator from `f-9qd-yosemite~ca~us` was removed, but Operator delete via changeset did not remove the `OperatorInFeed` record, which now referenced a missing record for operator_id. This can cause the FeedSerializer and other things to fail.

```
=> #<OperatorInFeed id: 200, gtfs_agency_id: "114", version: 1, created_at: "2016-03-19 00:21:50", updated_at: "2016-03-19 00:21:50", operator_id: 194, feed_id: 55, created_or_updated_in_changeset_id: 682>
```

Make `OperatorInFeed` records either dependent: destroy, or clean them up in `before_destroy_making_history`

**Comment by drewda** [comment]
Duplicate of #797 ?

**Comment by irees** [comment]
Good catch. Duplicate of #797
