### ISSUE TITLE
refactor computed properties

### ISSUE THREAD

**Issue by drewda** [transitland/transitland-datastore#829]
Right now computed properties are calculated in a single method, `changeset.update_computed_attributes`: https://github.com/transitland/transitland-datastore/blob/master/app/models/changeset.rb#L175-L219 As we add more computed properties, this will likely get even longer.

When we next computed properties, let's us the opportunity to refactor the code into a service like the `QualityCheck` service. There can be a base computed property class and individual definitions for each computed property.

**Comment by doublestranded** [comment]
- [ ] move rsp stop distance calc from GTFSGraph into new service. Keep distances derived from shape_dist_traveled in GTFSGraph (see #https://github.com/transitland/transitland-datastore/issues/987)
- [ ] move representative route computation into service from GTFSGraph
