### ISSUE TITLE
allow filtering of feed versions by calendar dates

### ISSUE THREAD

**Issue by drewda** [transitland/transitland-datastore#851]
`FeedVersion` models include information about the dates that they cover: `earliest_calendar_date` and `latest_calendar_date`. These properties are included in the public API responses: http://transit.land/api/v1/feed_versions Let's also allow users of this API endpoint to filter by date--this will make it possible to search through historic feed versions.

The following model scopes and API controller query parameters should provide enough flexibility:

- `calendar_coverage_begins_at_or_before`
- `calendar_coverage_begins_at_or_after`
- `calendar_coverage_includes`

TODO:
- [x] model scopes
- [x] query parameters in API controller
- [x] add indices to those columns in database?

**Comment by barbeau** [comment]
Filtering by date would be great!  

We’ve been archiving real-time GTFS-rt data, and now are trying to go back and piece together schedule data over that same time period as the timestamps in the real-time data.  So our typical use case for a request would be supplying a timestamp for the first GPS point in the dataset and a timestamp for the last GPS point in the dataset, and we would want to get back a list of GTFS datasets that cover that time period.  In other words, any trip_id in our GTFS-rt dataset would be guaranteed to exist in one of the returned GTFS datasets.  We would expect the parameters to be treated as inclusive (i.e., include the date specified in the parameter), which sounds like it matches with the proposed field names above.
