### ISSUE TITLE
run external validator libraries on new feed versions

### ISSUE THREAD

**Issue by drewda** [transitland/transitland-datastore#888]
When a new version of a feed is fetched from an agency server, we have the opportunity to run any number of validation libraries on the archive:

- [x] Google Python FeedValidator --> See #868 
- ~~[ ] `gtfs-validator` Java-based, originally by Conveyal, outputs a JSON payload that can be viewed in a front-end web client; latest version at https://github.com/conveyal/gtfs-validator/blob/master/gtfs-validator-json/README.md~~ no longer maintained
- [x] `conveyal/gtfs-lib` Java-based, by Conveyal, is the library they currently use and maintain for validating GTFS: https://github.com/conveyal/gtfs-lib
- ~~[ ] JSON Table Schema + Good Tables: https://github.com/Stephen-Gates/GTFS~~ holding for now, since this isn't ready for general use
- others to consider?

//cc @barbeau @antrim

**Comment by barbeau** [comment]
I've forked Stephen-Gates GTFS JSON Table Schema and started to generalize it for all GTFS consumers:
https://github.com/CUTR-at-USF/GTFS/blob/full-spec/datapackage.json

His schema was specific to South East Queensland and had a number of required fields to ensure their data was populated, but these should be optional when matching to the current spec.  He was also missing a number of fields, and a few tables still need to be filled in.

TODO for datapackage.json:
- [ ] - stop_times.txt
- [ ] - fare_attributes.txt
- [ ] - fare_rules.txt
- [ ] - frequencies.txt
- [ ] - transfers.txt

Open issue at https://github.com/CUTR-at-USF/GTFS/issues/1 - I'm happy to accept PRs there as well if others want to pitch in.  I'll keep chipping away at it as I have time.

**Comment by barbeau** [comment]
re: Conveyal gtfs-validator - we've gotten feedback from @sheldonabrown that he'd be willing to help get some of the changes by @laidig into the upstream Conveyal repo.  If possible I'd like to do that to avoid forking the project.  If not, I'd like to find a home for @laidig's changes in an organizational account where more than one person can be assigned to review/merge changes (we'd be willing to offer ours).

**Comment by drewda** [comment]
Learned from @mattwigway and @landonreed that instead of `conveyal/gtfs-validator` they now use `conveyal/gtfs-lib` to catch errors in GTFS feeds. When they're able to add a wrapper that can be called from the command line to produce validation output as JSON, then we'll set that up to run as part of Transitland's feed-fetch process.

**Comment by landonreed** [comment]
@drewda, the docs for `conveyal/gtfs-lib` have been updated with [CLI usage instructions](https://github.com/conveyal/gtfs-lib/#command-line).

**Comment by drewda** [comment]
Both the Google Python FeedValidator and Conveyal gtfs-lib are now run automatically on production servers.

For example: https://transit.land/dispatcher/feed-versions/12ff6497fb2f6c5a9f568ec80c4be6ef928b0957

One bug to resolve on production #1069
