### ISSUE TITLE
Remove Feed onestop_id from s3 filenames

### ISSUE THREAD

**Issue by irees** [transitland/transitland-datastore#895]
s3 files reference the onestop_id at the time of creation; if a Feed onestop_id is changed, the reference can be lost.

For s3 filenames:
[sha1].zip
[sha1]-raw.zip
[sha1]-validation.zip

See:
https://transit.land/dispatcher/feeds/f-dhvrs-bullrunner

**Comment by drewda** [comment]
This should happen as part of a `onestop_id_rename` action (related to: #794 #332 )

**Comment by drewda** [comment]
Upgrading the Carrierwave gem might help: https://github.com/transitland/transitland-datastore/issues/639

**Comment by drewda** [comment]
Related to the new `changeOnestopId` action happening as part of #332
