### ISSUE TITLE
FeedFetchService: Handle feedvalidator.py exceptions

### ISSUE THREAD

**Issue by irees** [transitland/transitland-datastore#900]
If feedvalidator.py has an exception, it will pause waiting for an enter from stdin. Find a workaround, either by disabling stdin (which seems to bypass the raw_input) or by sending in an enter by default.

**Comment by drewda** [comment]
Options for making the call from Ruby: http://stackoverflow.com/a/31572431/40956

**Comment by drewda** [comment]
Related to #888
