### ISSUE TITLE
Remove rake task for deleting unreferenced entities

### ISSUE THREAD

**Issue by doublestranded** [transitland/transitland-datastore#926]
Update the delete unreferenced entities rake task to ignore entities that were created through non-import changesets.

The scope: "where_not_imported_from_active_feed_version" needs to do this filtering.

**Comment by doublestranded** [comment]
Issues do need to be removed as well through the task. Ran the "db:cleanup:cleanup_unreferenced_entities" task 1/19/2017 and removed unreferenced issues on the console with the following code:

ids = EntityWithIssues.select(:entity).where(entity_type: 'RouteStopPattern').pluck(:entity_id) - RouteStopPattern.all.select(:id).pluck(:id)
EntityWithIssues.where(entity_id: ids, entity_type: 'RouteStopPattern').each(&:destroy)

**Comment by doublestranded** [comment]
Consider always outputting to a log file.

**Comment by doublestranded** [comment]
Remove rake task altogether.

**Comment by drewda** [comment]
Instead have feed imports selectively remove entities. For example: #907
