### ISSUE TITLE
Change exclude_geometry false default to include_geometry true

### ISSUE THREAD

**Issue by rmglennon** [transitland/transitland-datastore#939]
In release 55, there's a new property for `exclude_geometry`. See https://github.com/transitland/transitland-datastore/issues/866

If the default of `exclude_geometry` == `false`, it means the normal behavior is to return the geometry.

After some discussion, let's consider changing this to a positive so users don't have to think as much. We can do this by making it `include_geometry` and the default be `true`.

(The alternative suggestion was to make the property be something like `geometry` with values of `include` and `exclude` instead of a boolean, so do whatever is most consistent with other properties in the datastore.)

**Comment by doublestranded** [comment]
Make sure to keep backwards compatibility with 'exclude_geometry'.
