### ISSUE TITLE
Endpoint that redirects to download the latest version of a feed

### ISSUE THREAD

**Issue by drewda** [transitland/transitland-datastore#947]
If you want to download an archived version of a feed, you currently have to query the `/api/v1/feed_versions` endpoint, pluck out the appropriate `download_url`, and request the file from that URL.

To reduce the number of steps that repeat requesters need to make, we'll also offer an endpoint at `/api/v1/feeds/:onestop_id/download_latest_feed_version` that will redirect to the appropriate file on S3 with a `302 found` response.

//cc @LeoFR

**Comment by LeoFR** [comment]
@drewda Thanks! Should it be already live? If I get it right, the URL for BART should be:
`https://transit.land/api/v1/feeds/f-9q9-bart/download_latest_feed_version` 

But I got a `404`:
```{
"message": "No route matches GET /api/v1/feeds/f-9q9-bart/download_latest_feed_version"
}``

**Comment by drewda** [comment]
@LeoFR this has been merged into master, which deploys to our development server. So it's now possible to test at, for example: http://dev.transit.land/api/v1/feeds/f-9q9-bart/download_latest_feed_version

It will go on to production when https://github.com/transitland/transitland-datastore/pull/938 is merged.

**Comment by drewda** [comment]
@LeoFR this is now available on production servers. For example: https://transit.land/api/v1/feeds/f-9q9-bart/download_latest_feed_version
