### ISSUE TITLE
schedule_stop_pairs: date=today query param

### ISSUE THREAD

**Issue by irees** [transitland/transitland-datastore#965]
Allow "today" as a valid date, so links to the schedule API can always return the schedule for the current day.

Use the local time if an origin/destination stop is provided.

inspired by:
https://twitter.com/Piersoft/status/829944857128996864

**Comment by piersoft** [comment]
good. but today may have too data. better is "nexthour" . no?

**Comment by irees** [comment]
Timezones of course may complicate this. I know UTC day and time, but I don't know the day and time of the HTTP request unless it's specified by the user. I may only be able to provide this if a Stop or Operator is provided, from which I can pull the timezone.

**Comment by irees** [comment]
Hi @piersoft 

I implemented `date=today` for schedule_stop_pairs endpoint. I will add a `time=now` type feature in a follow-on PR.

**Comment by piersoft** [comment]
thanks a lot!

2017-03-06 23:17 GMT+01:00 Ian Rees <notifications@github.com>:

**Comment by irees** [comment]
@piersoft 

This will be available in the next production release. You can also use `now` in `origin_departure_between`, as well as `now+x`, `now-x`, where `x` is a number of seconds before or after the current local time.
