### ISSUE TITLE
Direct relationship between parent stations and stops/platforms?

### ISSUE THREAD

**Issue by markerpen** [transitland/transitland-datastore#971]
Hi all,

Noticed that in the `/api/v1/stops` endpoint, if I request a bounding box for a location (say New York), stops/platforms aren't connected in any way to their parent stations.

An example is **Grand Central  - 42nd** (a subway station). The API brings back three stops (edited for brevity):

```
{
            "identifiers": [],
            "onestop_id": "s-dr5ruds633-grandcentral~42st",
            "geometry": {
                "type": "Point",
                "coordinates": [
                    -73.976041,
                    40.751431
                ]
            },
            "name": "Grand Central - 42 St",
            "timezone": "America/New_York",
            "osm_way_id": 458177133,
            "served_by_vehicle_types": [],
            "operators_serving_stop": [],
            "routes_serving_stop": []
},
{
            "identifiers": [
                "gtfs://f-dr5r-nyctsubway/s/723S"
            ],
            "onestop_id": "s-dr5ruds633-grandcentral~42st<723s",
            "geometry": {
                "type": "Point",
                "coordinates": [
                    -73.976041,
                    40.751431
                ]
            },
            "name": "Grand Central - 42 St",
            "timezone": "America/New_York",
            "osm_way_id": 458177133,
            "served_by_vehicle_types": [
                "metro"
            ],
            "operators_serving_stop": [
                {
                    "operator_name": "MTA New York City Transit",
                    "operator_onestop_id": "o-dr5r-nyct"
                }
            ],
            "routes_serving_stop": [
                {
                    "operator_name": "MTA New York City Transit",
                    "operator_onestop_id": "o-dr5r-nyct",
                    "route_name": "7",
                    "route_onestop_id": "r-dr5r-7"
                },
                {
                    "operator_name": "MTA New York City Transit",
                    "operator_onestop_id": "o-dr5r-nyct",
                    "route_name": "7X",
                    "route_onestop_id": "r-dr5r-7x"
                }
            ]
},
{
            "identifiers": [
                "gtfs://f-dr5r-nyctsubway/s/723N"
            ],
            "onestop_id": "s-dr5ruds633-grandcentral~42st<723n",
            "geometry": {
                "type": "Point",
                "coordinates": [
                    -73.976041,
                    40.751431
                ]
            },
            "name": "Grand Central - 42 St",
            "timezone": "America/New_York",
            "osm_way_id": 458177133,
            "served_by_vehicle_types": [
                "metro"
            ],
            "operators_serving_stop": [
                {
                    "operator_name": "MTA New York City Transit",
                    "operator_onestop_id": "o-dr5r-nyct"
                }
            ],
            "routes_serving_stop": [
                {
                    "operator_name": "MTA New York City Transit",
                    "operator_onestop_id": "o-dr5r-nyct",
                    "route_name": "7",
                    "route_onestop_id": "r-dr5r-7"
                },
                {
                    "operator_name": "MTA New York City Transit",
                    "operator_onestop_id": "o-dr5r-nyct",
                    "route_name": "7X",
                    "route_onestop_id": "r-dr5r-7x"
                }
            ]
},
```

There are two issues here:

1. All three stops (the parent station and the two platforms) have exactly the same lat/long - if you were to place them on a map they would overlay each other.

2. I can see that the first stop is the parent station - and the other two are platforms. But how could I determine this in code? There's no direct relationship in the data between the platforms and the parent station. The way I'm working this out now is:

- If a stop doesn't have a GTFS identifier, it must be a parent station, and should have child platforms/stops.
- Check for any stops that start with the parent station's OneStopID with a `<` at the end - these will be children of that station
- Because the parent station doesn't have a `served_by_vehicle_types` element, use the child stops' `served_by_vehicle_types` as a hint to the parent station's transit mode.

Is this the best approach? And can there be a direct relationship between stations and stops within the API?

**Comment by drewda** [comment]
Thanks for your questions, @markerpen!

We're tackling the issues that you raise by developing a new endpoint at http://transit.land/api/v1/stop_stations This is still in progress--it's not finalized or fully documented--but you should be able to get a sense for how to more easily navigate the relationships among stations, platforms, and entrances.

We are avoiding major changes to the `/stops` endpoint. But to your 2nd issue, we could consider adding a `parent_stop_onestop_id` attribute to stops that have this information available. That would provide another, more direct, way of navigating the relationships.
